version: "2.4"

#
# [ volumes definition ]
#
# creates Docker volumes which can be mounted by other containers too e.g. for backup
#
volumes:
  # logs:
  #   name: homestead_logs
  files:
    name: homestead_files
  dbdata:
    name: homestead_dbdata
  dbs:
    name: homestead_dbs

#
# [ networks definition ]
#
# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge

services:
  #
  # [ server stack ]
  #
  # - nginx
  # - php-fpm
  # - oracle
  #
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    hostname: nginx

    cpu_shares: 128
    mem_reservation: 128m
    mem_limit: 256m
    memswap_limit: -1
    privileged: true
    restart: always

    environment:
      docker: "true"
      # https_proxy: "${https_proxy}"
      # http_proxy: "${http_proxy}"
      # ftp_proxy: "${ftp_proxy}"
      # no_proxy: "${no_proxy}"
      TZ: "America/Manaus"
      LANG: "pt_BR"
      LANGUAGE: "pt_BR:pt:en"

    ports:
      - 8080:80
      - 8443:443

    # working_dir: /usr/share/nginx/html
    working_dir: /opt/app-root/src

    volumes:
      - ./.docker/nginx/etc/tls:/etc/tls
      - ./.docker/nginx/etc/nginx/fastcgi_params.conf:/etc/nginx/fastcgi_params
      - ./.docker/nginx/etc/nginx/conf.d/homestead.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/usr/share/nginx/html:/usr/share/nginx/html
      # - ./docker/nginx/files:/opt/app-root/src/files
      - .:/opt/app-root/src
      - files:/opt/app-root/src/storage/app/public/files

    # depends_on:
    #   - php-fpm

    links:
      - php-fpm

    network_mode: bridge
    # networks:
    #   - frontend
    #   - backend

    command: nginx-debug -g 'daemon off;'

  php-fpm:
    image: rodrixcornell/php:7.4-oci-fpm
    container_name: php-fpm
    hostname: php-fpm

    cpu_shares: 128
    mem_reservation: 128m
    mem_limit: 256m
    memswap_limit: -1
    privileged: true
    restart: always

    env_file:
    - .env

    environment:
      docker: "true"
      # https_proxy: "${https_proxy}"
      # http_proxy: "${http_proxy}"
      # ftp_proxy: "${ftp_proxy}"
      # no_proxy: "${no_proxy}"
      TZ: "America/Manaus"
      LANG: "pt_BR"
      LANGUAGE: "pt_BR:pt:en"
      APP_TZ: "America/Manaus"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "oracle"
      DB_HOST: "oracle"
      DB_PORT: "1521"
      DB_SERVICE_NAME: "xe"
      DB_DATABASE: "xe"
      DB_USERNAME: "homestead"
      DB_PASSWORD: "secret"
      DB_CHARSET: "AL32UTF8"

    # ports:
    #   - 9009:9000

    extra_hosts:
      - pitua:172.17.104.15
      - curuduri:172.17.131.45
      - cubatao:172.17.131.4
      - divisa:172.17.131.24
      - jaragua:172.17.131.44
      - ararangua:172.17.135.110

    # working_dir: /var/www
    # working_dir: /api
    working_dir: /opt/app-root/src

    volumes:
      # - .:/var/www
      - .:/opt/app-root/src
      - /tmp:/opt/app-root/src/storage/logs
      - /tmp:/opt/app-root/src/storage/framework/views
      - /tmp:/opt/app-root/src/storage/framework/testing
      - /tmp:/opt/app-root/src/storage/framework/sessions
      - /tmp:/opt/app-root/src/storage/framework/cache/data
      # - ./docker/php/files:/opt/app-root/src/public/files
      - files:/opt/app-root/src/storage/app/public/files

    # depends_on:
    #   - oracle

    links:
      - oracle

    network_mode: bridge
    # networks:
    #   - backend

  oracle:
    image: rodrixcornell/oracle:11.2.0.2-xe
    container_name: oracle
    hostname: oracle

    cpu_shares: 512
    shm_size: 1g
    mem_reservation: 512m
    mem_limit: 2g
    memswap_limit: -1
    privileged: true
    restart: always

    environment:
      TZ: "America/Manaus"
      LANG: "pt_BR"
      LANGUAGE: "pt_BR:pt:en"
      # ORACLE_SID: "homestead" # default: ORCLCDB
      # ORACLE_PDB: "homestead" # default: ORCLPDB1
      ORACLE_PWD: "secret" # default: auto generated
      # ORACLE_CHARACTERSET: "AL32UTF8" # default: AL32UTF8

    ports:
      - "1521:1521"
      - "15210:8080"

    working_dir: /u01/app/oracle

    volumes:
      - ./.docker/oracle/initial_data:/docker-entrypoint-initdb.d/setup
      # - ./.docker/oracle/initial_data:/docker-entrypoint-initdb.d/startup
      - dbdata:/u01/app/oracle/oradata # persistent oracle database data.
      - dbs:/u01/app/oracle/product/11.2.0/xe/dbs

    network_mode: bridge
    # networks:
    #   - backend
